<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<?php
    $_share=$this->getItem();
    $_helper = $this->helper(BARANIUK_SHARES::HELPER_HTML);

?>

<?php if ($_share && $_share->getStatus() == 2 && $_share->getIsActive() ) : ?>

<div class="share-body">
    <?php
        if (!filter_var(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getImage($_share), FILTER_VALIDATE_URL)) {
            $image = explode('index.php/',Mage::getBaseUrl())[0].'media/'.Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getImage($_share);
        } else {
            $image = Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getImage($_share);
        }
    ?>
    <div class="photo" style="background-image: url('<?php echo $image ?>')"></div>
    <h1>
        <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getTitle($_share) ?>
        <span>
            FROM
            <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->filterDate(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getStartDate($_share)) ?>
            <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->filterDate(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getEndDate($_share)) ? 'TO' : '' ?>
            <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->filterDate(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getEndDate($_share)) ?>
        </span>
    </h1>
    <p class="description">
        <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getDescription($_share) ?>
    </p>
</div>

<?php else : ?>

<div class="is-empty">
    NOT FOUND
</div>

<?php endif; ?>

<style>

.share-body {
width: 100%;
height: 100%;
border-radius: 5px;
background-color: #343434;
padding: 10px;
color: white;
min-height: 320px;
}

.share-body .photo {
border-radius: 5px 0 0 0;
background-color: white;
margin-right: 10px;
width: 300px;
height: 300px;
float: left;
background-size: cover;
background-position: center;
}

.share-body h1 {
background-color: white;
padding: 10px;
border-radius: 5px;
}

.share-body h1 span {
float: right;
font-size: 15px;
}

.share-body .description {
padding: 10px;
text-align: justify;
}

.is-empty {
    padding: 50px;
    text-align: center;
    margin: auto;
    background-color: #343434;
    color: white;
    font-size: 20px;
}

</style>

<script>

</script>