<?php
    $_sharesCollection=$this->getCollection();
    $_helper = $this->helper('baraniuk_shares/helper');
?>

<?php if (!empty($_sharesCollection->getData())) : ?>

<?php echo $this->getToolbarHtml() ?>

<div class="share-block">
    <?php foreach ($_sharesCollection as $_share) : ?>
        <div class="share-item" onclick="openSharePage('<?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getLink($_share) ?>')">
            <?php
                if (!filter_var(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getImage($_share), FILTER_VALIDATE_URL)) {
                    $image = explode('index.php/',Mage::getBaseUrl())[0].'media/'.Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getImage($_share);
                } else {
                    $image = Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getImage($_share);
                }
            ?>
            <div class="photo" style="background-image: url('<?php echo $image ?>')">
            </div>
            <div class="info">
                <div class="datetime">
                    <div class="date">
                        FROM
                        <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->filterDate(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getStartDate($_share)) ?>
                        <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->filterDate(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getEndDate($_share)) ? 'TO' : '' ?>
                        <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->filterDate(Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getEndDate($_share)) ?>
                    </div>
                    <hr class="separator">
                </div>
                <div class="name">
                    <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getTitle($_share) ?>
                </div>
                <div class="description">
                    <?php echo Mage::helper( BARANIUK_SHARES::HELPER_HTML )->getShortDescription($_share) ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="toolbar-bottom">
    <?php echo $this->getToolbarHtml() ?>
</div>

<?php else : ?>

<div class="is-empty">
    NOTHING to output :)
</div>

<?php endif; ?>

<style>
    .share-block {
       display: flex;
       flex-wrap: wrap;
    }

    .share-item:hover {
        -webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
        -moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
        box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
    }

    .share-item:first-child {
        margin-top: 0;
    }

    .share-item {
        cursor: pointer;
        border-radius: 5px;
        transition: 0.3s;
        margin: 1%;
        background-color: #ffffff;
        width: 98%;
        height: 200px;
        display: flex;
    }

    .photo {
        background-color: #343434;
        border-radius: 5px 0 0 5px;
        width: 200px;
        height: 200px;
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }

    .info {
        width: calc(100% - 200px);
        height: 100%;
        padding: 10px;
        padding-left: 0;
        background-color: #343434;
        border-radius: 0 5px 5px 0;
        color: white;
    }

    .info .datetime {
        width: 100%;
    }

    .info .datetime .date {
        width: 100%;
        padding-left: 10px;
        font-size: 17px;
        text-align: left;
    }

    .info .datetime .time {
        padding-left: 10px;
        width: 100%;
        font-size: 12px;
        text-align: left;
    }

    .info .datetime .separator {
        width: calc(100% - 10px);
        margin-top: 10px;
        margin-left: 10px;
    }

    .info .name {
        padding: 10px;
        padding-bottom: 5px;
        font-size: 20px;
        text-transform: uppercase;
    }

    .info .description {
        padding: 10px;
        padding-top: 0;
        overflow-y: scroll;
        height: 100px;
    }

   @media only screen and (max-width: 640px) {
        .share-item {
            height: 100%;
            display: block;
        }

        .photo {
            border-radius: 5px 5px 0 0 ;
            width: 100% !important;
        }

        .info {
            width: 100%;
            border-radius: 0 0 5px 5px;
        }

        .info .description {
            height: 100%;
            overflow: auto;
        }
    }

    .is-empty {
        padding: 50px;
        text-align: center;
        margin: auto;
        background-color: #343434;
        color: white;
        font-size: 20px;
    }
</style>

<script>
    function openSharePage ($link) {
        window.location.href = $link;
    }
</script>
